INSERT INTO passwords (WEBSITE_NAME, WEBSITE_USERNAME, WEBSITE_PASSWORD, ORGANIZATION_ID, CATAGORY_ID)
VALUES ('zoom', 'Lighthouse-LHL', 'LL6Pcl/zTAILJ8iisP6EcTp05FYWPyJwscx66R6liuU=', 1, 2);

INSERT INTO passwords (WEBSITE_NAME, WEBSITE_USERNAME, WEBSITE_PASSWORD, ORGANIZATION_ID, CATAGORY_ID)
VALUES ('slack', 'Lighthouse-LHL', 'LL6Pcl/zTAILJ8iisP6EcTp05FYWPyJwscx66R6liuU=', 1, 2);

INSERT INTO passwords (WEBSITE_NAME, WEBSITE_USERNAME, WEBSITE_PASSWORD, ORGANIZATION_ID, CATAGORY_ID)
VALUES ('compass', 'Lighthouse-LHL', 'LL6Pcl/zTAILJ8iisP6EcTp05FYWPyJwscx66R6liuU=', 1, 2);

INSERT INTO passwords (WEBSITE_NAME, WEBSITE_USERNAME, WEBSITE_PASSWORD, ORGANIZATION_ID, CATAGORY_ID)
VALUES ('twitter', 'LighthouseLabs', 'LL6Pcl/zTAILJ8iisP6EcTp05FYWPyJwscx66R6liuU=', 1, 1);